### ISSUE TITLE
Support for gradients

### ISSUE THREAD

**Issue by Harshil783** [PaulleDemon/tkStyleSheet#3]
The package seems to be support only solid colors, it would be nice if support for gradients would be added

**Comment by PaulleDemon** [comment]
Hello @Harshil783 , Tkinter doesn't have built-in support for gradients. This package is only made to simplify the process of styling the tkinter application, this doesn't in any way provide additional functionalities such as gradients, animations etc. If you have any further questions let me know. Oh! and if you want to use Gradients you're probably better of with PyQt framework. Thank you.

**Comment by Harshil783** [comment]
No problem, I got that seems like tkinter is still bit lacking in design areas.
For PyQt I take that in mind.
